/**
 * The indicator catalogue.
 *
 * Every metric the app can show or score is defined here and seeded into the
 * `Indicator` table. Nothing downstream — the refresh script, the scoring
 * engine, the city page — hardcodes a metric; they all read this table. Adding
 * a metric means adding a row here and re-running the seed and refresh.
 *
 * `availableAtDistrict` was established empirically: the nine city-level
 * indicators GUS does not publish per dzielnica are marked false so the Warsaw
 * district panel can render them as "not published at district level" instead
 * of quietly omitting them.
 */

export type IndicatorSeed = {
  code: string;
  bdlVarId: number | null;
  source: "GUS_BDL" | "GIOS" | "OPEN_METEO" | "DERIVED";
  theme: "EARNINGS" | "HOUSING" | "LABOUR" | "SAFETY" | "ENVIRONMENT" | "LIVING";
  role: "SCORED" | "DISPLAY_ONLY" | "INPUT";
  direction: "BENEFIT" | "COST";
  /** Polish unit, as GUS publishes it. */
  unit: string;
  /** English equivalent shown in the English interface. */
  unitEn: string;
  labelPl: string;
  labelEn: string;
  descPl?: string;
  descEn?: string;
  availableAtDistrict: boolean;
  /** Omit to treat a stored zero as "not published". See schema.prisma. */
  zeroIsMissing?: boolean;
  sortOrder: number;
};

export const INDICATORS: IndicatorSeed[] = [
  // --- Earnings & economy ---------------------------------------------------
  {
    code: "avg_salary",
    bdlVarId: 64428,
    source: "GUS_BDL",
    theme: "EARNINGS",
    role: "SCORED",
    direction: "BENEFIT",
    unit: "PLN",
    unitEn: "PLN",
    labelPl: "Przeciętne wynagrodzenie brutto",
    labelEn: "Average gross monthly salary",
    descPl: "Przeciętne miesięczne wynagrodzenie brutto w sektorze przedsiębiorstw.",
    descEn: "Average gross monthly salary in the enterprise sector.",
    availableAtDistrict: false,
    sortOrder: 1,
  },
  {
    code: "salary_vs_national",
    bdlVarId: 64429,
    source: "GUS_BDL",
    theme: "EARNINGS",
    role: "SCORED",
    direction: "BENEFIT",
    unit: "Polska = 100",
    unitEn: "Poland = 100",
    labelPl: "Wynagrodzenie na tle kraju",
    labelEn: "Salary relative to national average",
    descPl: "Przeciętne wynagrodzenie w relacji do średniej krajowej (Polska = 100).",
    descEn: "Average salary as a share of the national average (Poland = 100).",
    availableAtDistrict: false,
    sortOrder: 2,
  },
  {
    code: "regon_entities",
    bdlVarId: 60530,
    source: "GUS_BDL",
    theme: "EARNINGS",
    role: "SCORED",
    direction: "BENEFIT",
    unit: "na 10 tys.",
    unitEn: "per 10k",
    labelPl: "Podmioty gospodarcze",
    labelEn: "Registered businesses",
    descPl: "Podmioty wpisane do rejestru REGON na 10 tys. ludności.",
    descEn: "Entities in the REGON business register per 10,000 inhabitants.",
    availableAtDistrict: true,
    sortOrder: 3,
  },
  {
    code: "new_businesses",
    bdlVarId: 60529,
    source: "GUS_BDL",
    theme: "EARNINGS",
    role: "SCORED",
    direction: "BENEFIT",
    unit: "na 10 tys.",
    unitEn: "per 10k",
    labelPl: "Nowe firmy",
    labelEn: "Newly registered businesses",
    descPl: "Jednostki nowo zarejestrowane w rejestrze REGON na 10 tys. ludności.",
    descEn: "Newly registered REGON entities per 10,000 inhabitants.",
    availableAtDistrict: true,
    sortOrder: 4,
  },

  // --- Housing --------------------------------------------------------------
  {
    code: "price_per_m2",
    bdlVarId: 633692,
    source: "GUS_BDL",
    theme: "HOUSING",
    role: "SCORED",
    direction: "COST",
    unit: "PLN/m²",
    unitEn: "PLN/m²",
    labelPl: "Średnia cena za 1 m²",
    labelEn: "Average price per m²",
    descPl: "Średnia cena 1 m² lokalu mieszkalnego sprzedanego w transakcjach rynkowych.",
    descEn: "Average price per m² of apartments sold in market transactions.",
    availableAtDistrict: false,
    sortOrder: 1,
  },
  {
    code: "median_price_per_m2",
    bdlVarId: 633677,
    source: "GUS_BDL",
    theme: "HOUSING",
    role: "SCORED",
    direction: "COST",
    unit: "PLN/m²",
    unitEn: "PLN/m²",
    labelPl: "Mediana ceny za 1 m²",
    labelEn: "Median price per m²",
    descPl: "Mediana ceny 1 m² lokalu mieszkalnego — mniej wrażliwa na transakcje skrajne.",
    descEn: "Median price per m² — less sensitive to outlier transactions than the mean.",
    availableAtDistrict: false,
    sortOrder: 2,
  },
  {
    code: "area_per_person",
    bdlVarId: 60573,
    source: "GUS_BDL",
    theme: "HOUSING",
    role: "SCORED",
    direction: "BENEFIT",
    unit: "m²",
    unitEn: "m²",
    labelPl: "Powierzchnia mieszkania na osobę",
    labelEn: "Living area per person",
    descPl: "Przeciętna powierzchnia użytkowa mieszkania przypadająca na 1 osobę.",
    descEn: "Average usable dwelling area per inhabitant.",
    availableAtDistrict: true,
    sortOrder: 3,
  },
  {
    code: "affordability",
    bdlVarId: null,
    source: "DERIVED",
    theme: "HOUSING",
    role: "SCORED",
    direction: "COST",
    unit: "mies. / m²",
    unitEn: "months / m²",
    labelPl: "Ile pensji kosztuje 1 m²",
    labelEn: "Months of salary per m²",
    descPl: "Średnia cena 1 m² podzielona przez przeciętne wynagrodzenie brutto.",
    descEn: "Average price per m² divided by the average gross monthly salary.",
    availableAtDistrict: false,
    sortOrder: 4,
  },

  // --- Labour market --------------------------------------------------------
  {
    code: "unemployment_rate",
    bdlVarId: 461691,
    source: "GUS_BDL",
    theme: "LABOUR",
    role: "SCORED",
    direction: "COST",
    unit: "%",
    unitEn: "%",
    labelPl: "Stopa bezrobocia",
    labelEn: "Registered unemployment rate",
    descPl: "Stopa bezrobocia rejestrowanego, stan na grudzień.",
    descEn: "Registered unemployment rate, as of December.",
    availableAtDistrict: false,
    sortOrder: 1,
  },
  {
    code: "closed_businesses",
    bdlVarId: 60528,
    source: "GUS_BDL",
    theme: "LABOUR",
    role: "SCORED",
    direction: "COST",
    unit: "na 10 tys.",
    unitEn: "per 10k",
    labelPl: "Firmy wykreślone z rejestru",
    labelEn: "Businesses deregistered",
    descPl: "Jednostki wykreślone z rejestru REGON na 10 tys. ludności.",
    descEn: "Entities removed from the REGON register per 10,000 inhabitants.",
    availableAtDistrict: true,
    sortOrder: 2,
  },
  {
    code: "net_migration",
    bdlVarId: 1365234,
    source: "GUS_BDL",
    theme: "LABOUR",
    role: "SCORED",
    direction: "BENEFIT",
    unit: "osób",
    unitEn: "people",
    labelPl: "Saldo migracji",
    labelEn: "Net migration",
    descPl: "Saldo migracji ogółem — różnica między napływem a odpływem ludności.",
    descEn: "Net migration — arrivals minus departures. A proxy for where people choose to move.",
    availableAtDistrict: true,
    // A balance of exactly zero is a real result, not a gap in the data.
    zeroIsMissing: false,
    sortOrder: 3,
  },

  // --- Safety ---------------------------------------------------------------
  {
    code: "crimes_per_1000",
    bdlVarId: 398594,
    source: "GUS_BDL",
    theme: "SAFETY",
    role: "SCORED",
    direction: "COST",
    unit: "na 1000",
    unitEn: "per 1,000",
    labelPl: "Przestępstwa na 1000 mieszkańców",
    labelEn: "Recorded crimes per 1,000 inhabitants",
    descPl: "Przestępstwa stwierdzone przez Policję ogółem na 1000 mieszkańców.",
    descEn: "Crimes recorded by the Police per 1,000 inhabitants.",
    availableAtDistrict: false,
    sortOrder: 1,
  },

  // --- Environment ----------------------------------------------------------
  {
    code: "green_per_capita",
    bdlVarId: null,
    source: "DERIVED",
    theme: "ENVIRONMENT",
    role: "SCORED",
    direction: "BENEFIT",
    unit: "m²",
    unitEn: "m²",
    labelPl: "Tereny zieleni na mieszkańca",
    labelEn: "Green space per inhabitant",
    descPl: "Powierzchnia parków, zieleńców i zieleni osiedlowej przeliczona na mieszkańca.",
    descEn: "Area of parks and green space per inhabitant. Normalising by population keeps large cities from winning on raw hectares alone.",
    availableAtDistrict: false,
    sortOrder: 1,
  },
  {
    code: "sewerage_rate",
    bdlVarId: null,
    source: "DERIVED",
    theme: "ENVIRONMENT",
    role: "SCORED",
    direction: "BENEFIT",
    unit: "%",
    unitEn: "%",
    labelPl: "Dostęp do oczyszczalni ścieków",
    labelEn: "Population served by sewage treatment",
    descPl: "Udział ludności korzystającej z oczyszczalni ścieków.",
    descEn: "Share of the population connected to a sewage treatment plant.",
    // GUS reports the connected population for the city as a whole and enters
    // zero for every dzielnica, so this cannot be broken down.
    availableAtDistrict: false,
    sortOrder: 2,
  },
  {
    code: "cars_per_1000",
    bdlVarId: 60533,
    source: "GUS_BDL",
    theme: "ENVIRONMENT",
    role: "SCORED",
    direction: "COST",
    unit: "na 1000",
    unitEn: "per 1,000",
    labelPl: "Samochody osobowe na 1000 mieszkańców",
    labelEn: "Cars per 1,000 inhabitants",
    descPl: "Wskaźnik motoryzacji — pośrednia miara presji transportu na miasto.",
    descEn: "Motorisation rate, used here as a proxy for traffic pressure rather than prosperity.",
    availableAtDistrict: false,
    sortOrder: 3,
  },
  {
    code: "air_quality_index",
    bdlVarId: null,
    source: "GIOS",
    theme: "ENVIRONMENT",
    role: "SCORED",
    direction: "COST",
    unit: "indeks",
    unitEn: "index",
    labelPl: "Indeks jakości powietrza",
    labelEn: "Air quality index",
    descPl: "Polski indeks jakości powietrza GIOŚ, uśredniony ze wszystkich stacji w mieście.",
    descEn: "The Polish air quality index from GIOŚ, averaged across every measuring station in the city.",
    availableAtDistrict: false,
    sortOrder: 4,
  },
  {
    code: "pm25",
    bdlVarId: null,
    source: "GIOS",
    theme: "ENVIRONMENT",
    role: "SCORED",
    direction: "COST",
    unit: "µg/m³",
    unitEn: "µg/m³",
    labelPl: "Pył zawieszony PM2,5",
    labelEn: "PM2.5 concentration",
    descPl: "Stężenie pyłu zawieszonego PM2,5, uśrednione ze stacji pomiarowych w mieście.",
    descEn: "PM2.5 particulate concentration, averaged across the city's measuring stations.",
    availableAtDistrict: false,
    sortOrder: 5,
  },

  // --- Climate & living -----------------------------------------------------
  {
    code: "comfortable_days",
    bdlVarId: null,
    source: "OPEN_METEO",
    theme: "LIVING",
    role: "SCORED",
    direction: "BENEFIT",
    unit: "dni",
    unitEn: "days",
    labelPl: "Dni komfortowe",
    labelEn: "Comfortable days",
    descPl: "Liczba dni w roku ze średnią temperaturą między 15 a 25 °C.",
    descEn: "Days per year with a mean temperature between 15 and 25 °C.",
    availableAtDistrict: false,
    sortOrder: 1,
  },
  {
    code: "sunshine_hours",
    bdlVarId: null,
    source: "OPEN_METEO",
    theme: "LIVING",
    role: "SCORED",
    direction: "BENEFIT",
    unit: "godz.",
    unitEn: "hours",
    labelPl: "Usłonecznienie",
    labelEn: "Annual sunshine hours",
    descPl: "Suma godzin usłonecznienia w ciągu roku.",
    descEn: "Total hours of sunshine per year.",
    availableAtDistrict: false,
    sortOrder: 2,
  },
  {
    code: "rainy_days",
    bdlVarId: null,
    source: "OPEN_METEO",
    theme: "LIVING",
    role: "SCORED",
    direction: "COST",
    unit: "dni",
    unitEn: "days",
    labelPl: "Dni deszczowe",
    labelEn: "Rainy days",
    descPl: "Liczba dni w roku z opadem powyżej 1 mm.",
    descEn: "Days per year with more than 1 mm of precipitation.",
    availableAtDistrict: false,
    sortOrder: 3,
  },
  {
    code: "tourist_beds",
    bdlVarId: 1539658,
    source: "GUS_BDL",
    theme: "LIVING",
    role: "SCORED",
    direction: "BENEFIT",
    unit: "na 10 tys.",
    unitEn: "per 10k",
    labelPl: "Obiekty noclegowe",
    labelEn: "Tourist accommodation",
    descPl: "Turystyczne obiekty noclegowe na 10 tys. ludności.",
    descEn: "Tourist accommodation establishments per 10,000 inhabitants.",
    availableAtDistrict: false,
    // A town with no hotels genuinely scores zero here.
    zeroIsMissing: false,
    sortOrder: 4,
  },
  {
    code: "cinema_seats",
    bdlVarId: 73918,
    source: "GUS_BDL",
    theme: "LIVING",
    role: "SCORED",
    direction: "COST",
    unit: "osób / miejsce",
    unitEn: "people / seat",
    labelPl: "Mieszkańców na 1 miejsce w kinie",
    labelEn: "Inhabitants per cinema seat",
    descPl: "Liczba ludności przypadająca na jedno miejsce w kinach stałych. Niższa wartość oznacza lepszy dostęp.",
    descEn: "Population per seat in permanent cinemas. Lower means better access, so this is scored as a cost.",
    availableAtDistrict: true,
    sortOrder: 5,
  },
  {
    code: "pupils_per_1000",
    bdlVarId: null,
    source: "DERIVED",
    theme: "LIVING",
    role: "SCORED",
    direction: "BENEFIT",
    unit: "na 1000",
    unitEn: "per 1,000",
    labelPl: "Uczniowie szkół podstawowych na 1000 mieszkańców",
    labelEn: "Primary school pupils per 1,000 inhabitants",
    descPl: "Pośrednia miara udziału młodych rodzin w populacji miasta.",
    descEn: "A proxy for how many young families the city holds.",
    availableAtDistrict: true,
    sortOrder: 6,
  },

  // --- Shown but never scored ----------------------------------------------
  {
    code: "population",
    bdlVarId: 72305,
    source: "GUS_BDL",
    theme: "LIVING",
    role: "DISPLAY_ONLY",
    direction: "BENEFIT",
    unit: "osób",
    unitEn: "people",
    labelPl: "Ludność",
    labelEn: "Population",
    descPl: "Liczba ludności ogółem. Podawana informacyjnie — nie podlega ocenie.",
    descEn: "Total population. Shown for context; ranking cities by size would say nothing about quality of life.",
    availableAtDistrict: true,
    sortOrder: 0,
  },

  // --- Denominators, never shown on their own -------------------------------
  {
    code: "green_area_ha",
    bdlVarId: 73791,
    source: "GUS_BDL",
    theme: "ENVIRONMENT",
    role: "INPUT",
    direction: "BENEFIT",
    unit: "ha",
    unitEn: "ha",
    labelPl: "Tereny zieleni (ha)",
    labelEn: "Green area (ha)",
    availableAtDistrict: false,
    sortOrder: 90,
  },
  {
    code: "pop_on_treatment",
    bdlVarId: 2119,
    source: "GUS_BDL",
    theme: "ENVIRONMENT",
    role: "INPUT",
    direction: "BENEFIT",
    unit: "osób",
    unitEn: "people",
    labelPl: "Ludność korzystająca z oczyszczalni",
    labelEn: "Population served by treatment plants",
    availableAtDistrict: false,
    sortOrder: 91,
  },
  {
    code: "primary_pupils",
    bdlVarId: 862,
    source: "GUS_BDL",
    theme: "LIVING",
    role: "INPUT",
    direction: "BENEFIT",
    unit: "osób",
    unitEn: "people",
    labelPl: "Uczniowie szkół podstawowych",
    labelEn: "Primary school pupils",
    availableAtDistrict: true,
    sortOrder: 92,
  },
];

/** BDL variables the refresh script needs to pull. */
export const BDL_VAR_IDS = INDICATORS.filter((i) => i.bdlVarId !== null).map(
  (i) => i.bdlVarId as number,
);
